# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimanager', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text="The player's name.", max_length=255)),
                ('number', models.PositiveSmallIntegerField(help_text="The player's number.")),
                ('team', models.ForeignKey(help_text='The team that the player belongs to.', on_delete=django.db.models.deletion.CASCADE, related_name='players', related_query_name='player', to='ultimanager.Team')),
            ],
            options={
                'verbose_name_plural': 'players',
                'verbose_name': 'player',
            },
        ),
    ]
