# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 09:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimanager', '0002_player'),
    ]

    operations = [
        migrations.CreateModel(
            name='Game',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opponent', models.CharField(help_text='The name of the opposing team.', max_length=255)),
                ('starting_position', models.CharField(choices=[('O', 'Defense'), ('D', 'Offense')], help_text='The position that the home team started the game on.', max_length=1)),
                ('team', models.ForeignKey(help_text='The team being tracked in the game.', on_delete=django.db.models.deletion.CASCADE, related_name='games', related_query_name='game', to='ultimanager.Team')),
            ],
        ),
    ]
