# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimanager', '0003_game'),
    ]

    operations = [
        migrations.CreateModel(
            name='Point',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_position', models.CharField(choices=[('D', 'Defense'), ('O', 'Offense')], help_text='The position that the home team is starting the point on.', max_length=1)),
                ('status', models.CharField(choices=[('P', 'In Progress'), ('H', 'Home Team Scored'), ('O', 'Opposing Team Scored')], help_text='The state that the point is in. If the point is complete, this field tracks which team scored.', max_length=1)),
            ],
            options={
                'verbose_name': 'point',
                'verbose_name_plural': 'points',
            },
        ),
        migrations.AlterField(
            model_name='game',
            name='starting_position',
            field=models.CharField(choices=[('D', 'Defense'), ('O', 'Offense')], help_text='The position that the home team started the game on.', max_length=1),
        ),
        migrations.AddField(
            model_name='point',
            name='game',
            field=models.ForeignKey(help_text='The game that the point is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='points', related_query_name='point', to='ultimanager.Game'),
        ),
        migrations.AddField(
            model_name='point',
            name='players',
            field=models.ManyToManyField(help_text='The players that played the point.', related_name='points', related_query_name='point', to='ultimanager.Player'),
        ),
    ]
