# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-11 10:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ultimanager', '0004_point'),
    ]

    operations = [
        migrations.CreateModel(
            name='Possession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(choices=[('D', 'Got a D'), ('P', 'Pulled to'), ('T', 'Turnover')], help_text='The reason the possession was started.', max_length=1)),
                ('defensive_player', models.ForeignKey(blank=True, help_text='The player who go the D to start the possession.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='defensive_possessions', related_query_name='defensive_possession', to='ultimanager.Player')),
                ('point', models.ForeignKey(help_text='The point the possession is a part of.', on_delete=django.db.models.deletion.CASCADE, related_name='possessions', related_query_name='possession', to='ultimanager.Point')),
            ],
            options={
                'verbose_name': 'possession',
                'verbose_name_plural': 'possessions',
            },
        ),
    ]
