---
# Django App Config

app_name: comp426-api
app_package: api

app_repo: 'https://github.com/cdriehuys/comp426-api'

app_required_packages:
  - libjpeg-turbo8
  - libpq-dev
  - zlib1g

django_requirements: "{{ django_project }}/requirements/production.txt"
django_secret_key: "{{ vault_django_secret_key }}"
django_settings_module: api.production_settings

django_databases:
  default:
    ENGINE: django.db.backends.postgresql_psycopg2
    NAME: "{{ db_name }}"
    USER: "{{ db_user }}"
    PASSWORD: "{{ db_password }}"
    HOST: localhost
    PORT: 5432

django_manage_commands:
  - collectstatic --noinput


# Letsencrypt
letsencrypt_email: chathan@driehuys.com
letsencrypt_renew_hour: 3
letsencrypt_renew_minute: 23


# NGINX Config

nginx_socket: 'http://{{ gunicorn_socket_unix }}'

nginx_site_servers:
  - listen: 80
    name: "{{ inventory_hostname }}"
    extra_params: |
          return 301 https://$server_name$request_uri;
  - listen: 443 ssl http2
    name: "{{ inventory_hostname }}"
    extra_params: |
          # Allow upload of large pictures
          client_max_body_size 5M;

          ssl_certificate {{ letsencrypt_live_dir }}/fullchain.pem;
          ssl_certificate_key {{ letsencrypt_live_dir }}/privkey.pem;

          # from https://cipherli.st/
          # and https://raymii.org/s/tutorials/Strong_SSL_Security_On_nginx.html
          ssl_protocols TLSv1 TLSv1.1 TLSv1.2;
          ssl_prefer_server_ciphers on;
          ssl_ciphers "EECDH+AESGCM:EDH+AESGCM:AES256+EECDH:AES256+EDH";
          ssl_ecdh_curve secp384r1;
          ssl_session_cache shared:SSL:10m;
          ssl_session_tickets off;
          ssl_stapling on;
          ssl_stapling_verify on;
          resolver 8.8.8.8 8.8.4.4 valid=300s;
          resolver_timeout 5s;
          # Disable preloading HSTS for now.  You can use the commented out header line that includes
          # the "preload" directive if you understand the implications.
          #add_header Strict-Transport-Security "max-age=63072000; includeSubdomains; preload";
          add_header Strict-Transport-Security "max-age=63072000; includeSubdomains";
          add_header X-Frame-Options DENY;
          add_header X-Content-Type-Options nosniff;

          ssl_dhparam {{ letsencrypt_dh_group }};

          location = /favicon.ico {
            access_log off;
          }

          location /media/ {
            alias {{ django_media_root }}/;
          }

          location /static/ {
            alias {{ django_static_root }}/;
          }

          location / {
            include proxy_params;
            proxy_pass {{ nginx_socket }};
          }
